Weather Prediction Model - Buhari Adamu

A predictive model that uses time features and lagged features to predict temperature and humidity.
The data produced is feed into the Demand Predictive Model.

In [1]:
import pandas as pd

In [2]:
file_name1="Demand_Dataset_Post_Prep.csv"

try:
    weather_df=pd.read_csv(file_name1)
    print(f"The file \"{file_name1}\" was loaded successfully.")
except Exception as e:
    print(f"An error occurred while loading the file \"{file_name1}\":\n{e}")

The file "Demand_Dataset_Post_Prep.csv" was loaded successfully.

In [3]:
weather_df2=weather_df.drop(columns=["Demand", "Demand_Lag_1H", "Demand_Lag_24H", "Demand_Lag_1W", "Demand_Lag_1M", "Rolling_Mean_24H_(Demand)", "Rolling_Std_24H_(Demand)"])

In [4]:
weather_df2

,Timestamp,hour,dayofweek,month,year,dayofyear,weekofyear,weekend,quarter,Temperature,Humidity
0,2020-01-29,0.0,2.0,1.0,2020.0,29.0,5,0,1,3.000000,43.542449
1,2020-01-29,1.0,2.0,1.0,2020.0,29.0,5,0,1,3.000000,61.993876
2,2020-01-29,2.0,2.0,1.0,2020.0,29.0,5,0,1,3.910297,60.060009
3,2020-01-29,3.0,2.0,1.0,2020.0,29.0,5,0,1,5.757228,49.535875
4,2020-01-29,4.0,2.0,1.0,2020.0,29.0,5,0,1,5.807415,59.151179
...,...,...,...,...,...,...,...,...,...,...,...
43167,2024-12-31,19.0,1.0,12.0,2024.0,366.0,1,0,4,3.956838,43.287161
43168,2024-12-31,20.0,1.0,12.0,2024.0,366.0,1,0,4,3.118824,51.705756
43169,2024-12-31,21.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,40.565916
43170,2024-12-31,22.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,51.998107
43171,2024-12-31,23.0,1.0,12.0,2024.0,366.0,1,0,4,6.037472,59.931925

In [5]:
weather_df2["Timestamp"]=pd.to_datetime(weather_df2["Timestamp"])

In [6]:
weather_df2=weather_df2.set_index("Timestamp")

In [7]:
weather_df2

,hour,dayofweek,month,year,dayofyear,weekofyear,weekend,quarter,Temperature,Humidity
Timestamp,,,,,,,,,,
2020-01-29,0.0,2.0,1.0,2020.0,29.0,5,0,1,3.000000,43.542449
2020-01-29,1.0,2.0,1.0,2020.0,29.0,5,0,1,3.000000,61.993876
2020-01-29,2.0,2.0,1.0,2020.0,29.0,5,0,1,3.910297,60.060009
2020-01-29,3.0,2.0,1.0,2020.0,29.0,5,0,1,5.757228,49.535875
2020-01-29,4.0,2.0,1.0,2020.0,29.0,5,0,1,5.807415,59.151179
...,...,...,...,...,...,...,...,...,...,...
2024-12-31,19.0,1.0,12.0,2024.0,366.0,1,0,4,3.956838,43.287161
2024-12-31,20.0,1.0,12.0,2024.0,366.0,1,0,4,3.118824,51.705756
2024-12-31,21.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,40.565916
2024-12-31,22.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,51.998107
2024-12-31,23.0,1.0,12.0,2024.0,366.0,1,0,4,6.037472,59.931925

In [8]:
weather_df2.insert(9, "Temperature_Lagged_1H", weather_df2["Temperature"].shift(1))

In [9]:
weather_df2.insert(10, "Temperature_Lagged_1D", weather_df2["Temperature"].shift(24))

In [10]:
weather_df2.insert(11, "Temperature_Lagged_1W", weather_df2["Temperature"].shift(168))

In [11]:
weather_df2.insert(12, "Temperature_Lagged_1M", weather_df2["Temperature"].shift(672))

In [12]:
weather_df2.insert(14, "Humidity_Lagged_1H", weather_df2["Humidity"].shift(1))

In [13]:
weather_df2.insert(15, "Humidity_Lagged_1D", weather_df2["Humidity"].shift(24))

In [14]:
weather_df2.insert(16, "Humidity_Lagged_1W", weather_df2["Humidity"].shift(168))

In [15]:
weather_df2.insert(17, "Humidity_Lagged_1M", weather_df2["Humidity"].shift(672))

In [16]:
weather_df2

,hour,dayofweek,month,year,dayofyear,weekofyear,weekend,quarter,Temperature,Temperature_Lagged_1H,Temperature_Lagged_1D,Temperature_Lagged_1W,Temperature_Lagged_1M,Humidity,Humidity_Lagged_1H,Humidity_Lagged_1D,Humidity_Lagged_1W,Humidity_Lagged_1M
Timestamp,,,,,,,,,,,,,,,,,,
2020-01-29,0.0,2.0,1.0,2020.0,29.0,5,0,1,3.000000,NaN,NaN,NaN,NaN,43.542449,NaN,NaN,NaN,NaN
2020-01-29,1.0,2.0,1.0,2020.0,29.0,5,0,1,3.000000,3.000000,NaN,NaN,NaN,61.993876,43.542449,NaN,NaN,NaN
2020-01-29,2.0,2.0,1.0,2020.0,29.0,5,0,1,3.910297,3.000000,NaN,NaN,NaN,60.060009,61.993876,NaN,NaN,NaN
2020-01-29,3.0,2.0,1.0,2020.0,29.0,5,0,1,5.757228,3.910297,NaN,NaN,NaN,49.535875,60.060009,NaN,NaN,NaN
2020-01-29,4.0,2.0,1.0,2020.0,29.0,5,0,1,5.807415,5.757228,NaN,NaN,NaN,59.151179,49.535875,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31,19.0,1.0,12.0,2024.0,366.0,1,0,4,3.956838,10.469568,10.192890,14.245067,12.553244,43.287161,47.150478,68.580438,55.383583,77.949581
2024-12-31,20.0,1.0,12.0,2024.0,366.0,1,0,4,3.118824,3.956838,4.452914,9.434158,3.000000,51.705756,43.287161,42.628856,73.938216,73.705413
2024-12-31,21.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,3.118824,3.262666,3.449389,3.524350,40.565916,51.705756,28.093318,56.672841,52.811194
2024-12-31,22.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,3.000000,3.698432,3.000000,3.000000,51.998107,40.565916,64.397581,45.789633,70.325963
2024-12-31,23.0,1.0,12.0,2024.0,366.0,1,0,4,6.037472,3.000000,3.000000,9.374057,3.000000,59.931925,51.998107,50.410791,60.487943,69.969767

In [17]:
weather_df3=weather_df2.dropna()

In [18]:
weather_df3[weather_df3.isna().any(axis=1)]

Empty DataFrame
Columns: [hour, dayofweek, month, year, dayofyear, weekofyear, weekend, quarter, Temperature, Temperature_Lagged_1H, Temperature_Lagged_1D, Temperature_Lagged_1W, Temperature_Lagged_1M, Humidity, Humidity_Lagged_1H, Humidity_Lagged_1D, Humidity_Lagged_1W, Humidity_Lagged_1M]
Index: []

In [19]:
X=weather_df3.drop(columns=["Temperature", "Humidity"])

In [20]:
Y1=weather_df3.Temperature

Y1=Y1.to_frame()


Y2=weather_df3.Humidity

Y2=Y2.to_frame()


Y=pd.concat([Y1, Y2], axis=1)

In [21]:
X

,hour,dayofweek,month,year,dayofyear,weekofyear,weekend,quarter,Temperature_Lagged_1H,Temperature_Lagged_1D,Temperature_Lagged_1W,Temperature_Lagged_1M,Humidity_Lagged_1H,Humidity_Lagged_1D,Humidity_Lagged_1W,Humidity_Lagged_1M
Timestamp,,,,,,,,,,,,,,,,
2020-02-26,0.0,2.0,2.0,2020.0,57.0,9,0,1,8.399858,3.000000,3.685876,3.000000,41.456911,35.642492,50.516321,43.542449
2020-02-26,1.0,2.0,2.0,2020.0,57.0,9,0,1,6.120046,7.043426,3.296193,3.000000,46.420745,38.574834,36.654409,61.993876
2020-02-26,2.0,2.0,2.0,2020.0,57.0,9,0,1,6.295186,6.423205,8.145409,3.910297,26.271206,46.323436,38.145670,60.060009
2020-02-26,3.0,2.0,2.0,2020.0,57.0,9,0,1,6.448815,8.994551,13.516858,5.757228,55.053718,58.342130,53.849786,49.535875
2020-02-26,4.0,2.0,2.0,2020.0,57.0,9,0,1,11.475982,13.581523,14.854241,5.807415,66.139032,59.089831,52.966278,59.151179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31,19.0,1.0,12.0,2024.0,366.0,1,0,4,10.469568,10.192890,14.245067,12.553244,47.150478,68.580438,55.383583,77.949581
2024-12-31,20.0,1.0,12.0,2024.0,366.0,1,0,4,3.956838,4.452914,9.434158,3.000000,43.287161,42.628856,73.938216,73.705413
2024-12-31,21.0,1.0,12.0,2024.0,366.0,1,0,4,3.118824,3.262666,3.449389,3.524350,51.705756,28.093318,56.672841,52.811194
2024-12-31,22.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,3.698432,3.000000,3.000000,40.565916,64.397581,45.789633,70.325963
2024-12-31,23.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,3.000000,9.374057,3.000000,51.998107,50.410791,60.487943,69.969767

In [50]:
X.to_csv("X_Weather_Dataset.csv")

In [22]:
Y

            Temperature   Humidity
Timestamp
2020-02-26     6.120046  46.420745
2020-02-26     6.295186  26.271206
2020-02-26     6.448815  55.053718
2020-02-26    11.475982  66.139032
2020-02-26    15.145814  64.347355
...                 ...        ...
2024-12-31     3.956838  43.287161
2024-12-31     3.118824  51.705756
2024-12-31     3.000000  40.565916
2024-12-31     3.000000  51.998107
2024-12-31     6.037472  59.931925

[42500 rows x 2 columns]

In [23]:
X_train=X.loc[:"2023-12-01"]

X_test=X.loc["2024-01-01":]

In [24]:
Y_train=Y.loc[:"2023-12-01"]

Y_test=Y.loc["2024-01-01":]

In [25]:
X_train

,hour,dayofweek,month,year,dayofyear,weekofyear,weekend,quarter,Temperature_Lagged_1H,Temperature_Lagged_1D,Temperature_Lagged_1W,Temperature_Lagged_1M,Humidity_Lagged_1H,Humidity_Lagged_1D,Humidity_Lagged_1W,Humidity_Lagged_1M
Timestamp,,,,,,,,,,,,,,,,
2020-02-26,0.0,2.0,2.0,2020.0,57.0,9,0,1,8.399858,3.000000,3.685876,3.000000,41.456911,35.642492,50.516321,43.542449
2020-02-26,1.0,2.0,2.0,2020.0,57.0,9,0,1,6.120046,7.043426,3.296193,3.000000,46.420745,38.574834,36.654409,61.993876
2020-02-26,2.0,2.0,2.0,2020.0,57.0,9,0,1,6.295186,6.423205,8.145409,3.910297,26.271206,46.323436,38.145670,60.060009
2020-02-26,3.0,2.0,2.0,2020.0,57.0,9,0,1,6.448815,8.994551,13.516858,5.757228,55.053718,58.342130,53.849786,49.535875
2020-02-26,4.0,2.0,2.0,2020.0,57.0,9,0,1,11.475982,13.581523,14.854241,5.807415,66.139032,59.089831,52.966278,59.151179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-01,19.0,4.0,12.0,2023.0,335.0,48,0,4,3.964358,3.453388,12.800228,15.347185,43.220349,60.111177,56.464229,65.695822
2023-12-01,20.0,4.0,12.0,2023.0,335.0,48,0,4,11.546470,7.502532,9.372708,11.797110,58.240996,50.072885,63.970251,62.936997
2023-12-01,21.0,4.0,12.0,2023.0,335.0,48,0,4,9.408922,3.000000,4.676162,10.655926,62.247541,73.652041,75.410241,88.317925
2023-12-01,22.0,4.0,12.0,2023.0,335.0,48,0,4,3.000000,3.000000,3.000000,10.464035,44.202939,76.635914,41.412883,68.078403
2023-12-01,23.0,4.0,12.0,2023.0,335.0,48,0,4,3.874041,3.038499,9.567897,7.402131,72.721250,66.958377,77.663435,76.400596

In [26]:
Y_train

            Temperature   Humidity
Timestamp
2020-02-26     6.120046  46.420745
2020-02-26     6.295186  26.271206
2020-02-26     6.448815  55.053718
2020-02-26    11.475982  66.139032
2020-02-26    15.145814  64.347355
...                 ...        ...
2023-12-01    11.546470  58.240996
2023-12-01     9.408922  62.247541
2023-12-01     3.000000  44.202939
2023-12-01     3.874041  72.721250
2023-12-01     3.000000  61.336851

[32996 rows x 2 columns]

In [27]:
X_test

,hour,dayofweek,month,year,dayofyear,weekofyear,weekend,quarter,Temperature_Lagged_1H,Temperature_Lagged_1D,Temperature_Lagged_1W,Temperature_Lagged_1M,Humidity_Lagged_1H,Humidity_Lagged_1D,Humidity_Lagged_1W,Humidity_Lagged_1M
Timestamp,,,,,,,,,,,,,,,,
2024-01-01,0.0,0.0,1.0,2024.0,1.0,1,0,1,3.646036,3.000000,3.000000,3.000000,54.793612,66.776117,71.026861,73.412484
2024-01-01,1.0,0.0,1.0,2024.0,1.0,1,0,1,3.000000,3.000000,3.000000,4.193356,65.297046,72.919347,69.653522,73.021278
2024-01-01,2.0,0.0,1.0,2024.0,1.0,1,0,1,3.000000,3.000000,3.000000,3.000000,69.068654,57.857704,67.958995,69.481537
2024-01-01,3.0,0.0,1.0,2024.0,1.0,1,0,1,3.000000,3.183936,3.000000,3.000000,80.885372,91.517196,73.534458,61.881776
2024-01-01,4.0,0.0,1.0,2024.0,1.0,1,0,1,7.788675,5.944553,9.593859,6.487630,66.501527,55.600375,66.540642,79.813501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31,19.0,1.0,12.0,2024.0,366.0,1,0,4,10.469568,10.192890,14.245067,12.553244,47.150478,68.580438,55.383583,77.949581
2024-12-31,20.0,1.0,12.0,2024.0,366.0,1,0,4,3.956838,4.452914,9.434158,3.000000,43.287161,42.628856,73.938216,73.705413
2024-12-31,21.0,1.0,12.0,2024.0,366.0,1,0,4,3.118824,3.262666,3.449389,3.524350,51.705756,28.093318,56.672841,52.811194
2024-12-31,22.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,3.698432,3.000000,3.000000,40.565916,64.397581,45.789633,70.325963
2024-12-31,23.0,1.0,12.0,2024.0,366.0,1,0,4,3.000000,3.000000,9.374057,3.000000,51.998107,50.410791,60.487943,69.969767

In [28]:
Y_test

            Temperature   Humidity
Timestamp
2024-01-01     3.000000  65.297046
2024-01-01     3.000000  69.068654
2024-01-01     3.000000  80.885372
2024-01-01     7.788675  66.501527
2024-01-01     6.607828  57.858109
...                 ...        ...
2024-12-31     3.956838  43.287161
2024-12-31     3.118824  51.705756
2024-12-31     3.000000  40.565916
2024-12-31     3.000000  51.998107
2024-12-31     6.037472  59.931925

[8784 rows x 2 columns]

In [29]:
X_train_shape=X_train.shape
Y_train_shape=Y_train.shape

X_test_shape=X_test.shape
Y_test_shape=Y_test.shape

print(f"Shape of X_train:{X_train_shape}\nShape of Y_train:{Y_train_shape}\nShape of X_test:{X_test_shape}\nShape of Y_test:{Y_test_shape}")

Shape of X_train:(32996, 16)
Shape of Y_train:(32996, 2)
Shape of X_test:(8784, 16)
Shape of Y_test:(8784, 2)

Model Implementation

In [30]:
import xgboost as xgb

from xgboost import XGBRegressor

from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import mean_squared_error, mean_absolute_error

In [31]:
weather_predictive_model=XGBRegressor(
    n_estimators=1000,
    early_stopping_rounds=50,
    learning_rate=0.01,
    random_state=50,
    objective="reg:squarederror"
    
)

In [32]:
weather_predictive_model.fit(X_train, Y_train, eval_set=[(X_train, Y_train),(X_test, Y_test)], verbose=False)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=50,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=None, num_parallel_tree=None, ...)

In [33]:
import numpy as np

In [35]:
predictions=weather_predictive_model.predict(X_test)

sqrt_mse=np.sqrt(mean_squared_error(predictions, Y_test))

mae=mean_absolute_error(predictions, Y_test)

print(f"Square Root of Mean Squared Error: {sqrt_mse}\nMean Absolute Error: {mae}")

Square Root of Mean Squared Error: 7.238796654275704
Mean Absolute Error: 5.158570289611816

In [38]:
file_name="Weather_Predictive_Model.json"

try:
    weather_predictive_model.save_model(file_name)
    print(f"The model has been successfully saved as \"{file_name}\".")
except Exception as e:
    print(f"An error occurred while saving the model:\n{e}")


model=xgb.XGBRegressor()

model.load_model("Weather_Predictive_Model.json")

The model has been successfully saved as "Weather_Predictive_Model.json".

In [47]:
file_name_1="Weather_Model_Data.csv"
dataframe_name="weather_df3"

try:
    weather_df3.to_csv(file_name_1)
    print(f"The Dataframe \"{dataframe_name}\" has been saved as \"{file_name_1}\".")
except Exception as e:
    print(f"An error occurred while saving the dataframe \"{dataframe_name}\".\n{e}")

The Dataframe "weather_df3" has been saved as "Weather_Model_Data.csv".

In [ ]:


hour=





new_data=pd.Dataframe({
    "hour"=0,
    "dayofweek"=2
    "month"=1
    "year"=2025
    "dayofyear"=1
    "weekofyear"=1
    "weekend"=0
    "quarter"=1
    "Temperature_Lagged_1H"=6.037472
    "Temperature_Lagged_1D"=
    "Temperature_Lagged_1W"=
    "Temperature_Lagged_1M"=
    "Humidity_Lagged_1H"=59.931925
    "Humidity_Lagged_1D"=
    "Humidity_Lagged_1W"=
    "Humidity_Lagged_1M"=
})




 #hour: 
    0,
    #dayofweek: 
    2,
    #month: 
    1,
    #year: 
    2025,
    #dayofyear: 
    1,
    #weekofyear: 
    1,
    #weekend: 
    0,
    #quarter: 
    1,

 """
 Temperature_Lagged_1H:6.037472 ()
    Temperature_Lagged_1D: 3.0 (42477) (42,501-24)
    Temperature_Lagged_1W: (42333) (42,501-(24x7))
    Temperature_Lagged_1M: () (42,501-(24x7x4))
    Humidity_Lagged_1H:59.931925 () ()
    Humidity_Lagged_1D: 74.12431225 (42477)
    Humidity_Lagged_1W: (42333) ()
    Humidity_Lagged_1M: () ()
"""

In [48]:
print(len(Y_test))

8784